[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
engine = { path = "../../crates/engine" }

[features]
default = []
webgl = ["engine/webgl"]
webgpu = ["engine/webgpu"]
